FROM container-registry.oracle.com/os/oraclelinux:8-slim

ARG MYSQL_CLIENT_PACKAGE=mysql-community-client-8.4.4
ARG MYSQL_ROUTER_PACKAGE=mysql-router-community-8.4.4
ARG CONFIG_PACKAGE_NAME=mysql84-community-release-el8.rpm
ARG REPO_NAME_SERVER=mysql-8.4-lts-community
ARG REPO_NAME_TOOLS=mysql-tools-8.4-lts-community
ENV MYSQL_MAJOR=8.4
ENV MYSQL_VERSION=8.4.4-1.el8

RUN /usr/sbin/groupadd -g 999 -r mysqlrouter >/dev/null \
    && /usr/sbin/useradd -M -N -u 999 -g mysqlrouter -r -d /var/lib/mysqlrouter -s /bin/false \
    -c "MySQL Router" mysqlrouter
RUN set -eux; \
    microdnf install -y \
    bzip2 \
    gzip \
    openssl \
    xz \
    zstd \
    findutils \
    ; \
    # Set MySQL version and add repository
    { \
    echo '[mysql-8.4-community]'; \
    echo 'name=MySQL 8.4 Community'; \
    echo 'enabled=1'; \
    echo 'baseurl=https://repo.mysql.com/yum/mysql-8.4-community/el/8/$basearch/'; \
    echo 'gpgcheck=0'; \
    echo 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql'; \
    echo 'module_hotfixes=true'; \
    } | tee /etc/yum.repos.d/mysql-8.4-community.repo; \
    \
    # Install MySQL server
    microdnf install -y "mysql-community-client-$MYSQL_VERSION"; \
    microdnf clean all;
RUN set -eu; \
    { \
    echo '[mysql-tools-community]'; \
    echo 'name=MySQL Tools Community'; \
    echo 'baseurl=https://repo.mysql.com/yum/mysql-tools-8.4-community/el/8/$basearch/'; \
    echo 'enabled=1'; \
    echo 'gpgcheck=0'; \
    # https://github.com/docker-library/mysql/pull/680#issuecomment-825930524
    } | tee /etc/yum.repos.d/mysql-community-tools.repo
ENV MYSQL_ROUTER_VERSION 8.4.4-1.el8
RUN set -eux; \
    microdnf install -y "mysql-router-community-$MYSQL_ROUTER_VERSION"; \
    microdnf clean all; \
    \
    mysqlrouter --version

ADD --chmod=755 https://raw.githubusercontent.com/mysql/mysql-docker/refs/heads/main/mysql-router/8.4/run.sh /run.sh
HEALTHCHECK \
    CMD mysqladmin --port 6446 --protocol TCP ping 2>&1 | grep Access || exit 1
EXPOSE 6446 6447 6448 6449 6450 8443
USER 999:999
ENTRYPOINT ["/run.sh"]
CMD ["mysqlrouter"]